name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up system
      run: |
        sudo apt-get update
        sudo apt-get install -y php7.3-imagick
        mkdir tests/diffs
    - name: Allow Imagick to read/write PDFs
      run: sudo sed -i -e 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Execute tests
      run: vendor/bin/phpunit
